# Generated by Django 5.1 on 2024-08-28 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CategoryName", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PendingStudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BatchNo", models.CharField(max_length=100, null=True)),
                ("CourseName", models.CharField(max_length=100, null=True)),
                ("StudentName", models.CharField(max_length=100, null=True)),
                (
                    "StudentPhoto",
                    models.ImageField(null=True, upload_to="pendingstudentPhoto"),
                ),
                ("AdmissionDate", models.DateField(auto_now_add=True, null=True)),
                (
                    "EducationalQualification",
                    models.CharField(max_length=100, null=True),
                ),
                ("FatherName", models.CharField(max_length=100, null=True)),
                ("MotherName", models.CharField(max_length=100, null=True)),
                ("Religion", models.CharField(max_length=100, null=True)),
                ("DOB", models.DateField(null=True)),
                (
                    "Gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("Mobile", models.CharField(max_length=100, null=True)),
                ("EmergencyContact", models.CharField(max_length=100, null=True)),
                ("PresentAddress", models.CharField(max_length=100, null=True)),
                ("PermanentAddress", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebsiteContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Imsuser", models.CharField(max_length=50, null=True)),
                ("Mobile", models.CharField(max_length=50, null=True)),
                ("Address", models.CharField(max_length=100, null=True)),
                ("Email", models.CharField(max_length=100, null=True)),
                ("MapLink", models.TextField(null=True)),
                ("GithubLink", models.CharField(max_length=150, null=True)),
                ("FacebookLink", models.CharField(max_length=150, null=True)),
                ("YoutubeLink", models.CharField(max_length=150, null=True)),
                ("TwitterLink", models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CourseName", models.CharField(max_length=150, null=True)),
                ("Sologan", models.CharField(max_length=100, null=True)),
                ("ShortSummary", models.CharField(max_length=150, null=True)),
                ("Lecture", models.IntegerField(null=True)),
                ("CourseDuration", models.IntegerField(null=True)),
                ("WeeklyClass", models.IntegerField(null=True)),
                ("ClassDuration", models.IntegerField(null=True)),
                ("TotalProject", models.IntegerField(null=True)),
                ("CourseOverview", models.TextField(null=True)),
                ("CourseCurrriculum", models.TextField(null=True)),
                ("Software", models.TextField(max_length=200, null=True)),
                ("CourseFor", models.TextField(null=True)),
                ("JobPositions", models.TextField(null=True)),
                ("CourseFee", models.IntegerField(null=True)),
                ("IntroVideo", models.CharField(max_length=200, null=True)),
                ("CourseImage", models.ImageField(null=True, upload_to="courseImage")),
                (
                    "CourseCategory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coursecategory",
                        to="myApp.coursecategorymodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatchInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BatchNo", models.CharField(max_length=100, null=True)),
                ("Batchschedule", models.CharField(max_length=100, null=True)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("On-Going", "On-Going"),
                            ("Upcomming", "Upcomming"),
                            ("Completed", "Completed"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("BatchStartDate", models.DateField(null=True)),
                ("TotalStudent", models.CharField(max_length=100, null=True)),
                ("BatchInstructor", models.CharField(max_length=100, null=True)),
                (
                    "CourseName",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coursenameinfo",
                        to="myApp.courseinfomodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Password", models.CharField(max_length=100, null=True)),
                ("FatherName", models.CharField(max_length=100, null=True)),
                ("MotherName", models.CharField(max_length=100, null=True)),
                ("Religion", models.CharField(max_length=100, null=True)),
                ("DOB", models.DateField(null=True)),
                (
                    "Gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("Mobile", models.CharField(max_length=100, null=True)),
                ("EmergencyContact", models.CharField(max_length=100, null=True)),
                ("PresentAddress", models.CharField(max_length=100, null=True)),
                ("PermanentAddress", models.CharField(max_length=100, null=True)),
                (
                    "Imsuser",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalinfo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=150, null=True)),
                ("Salary", models.CharField(max_length=150, null=True)),
                ("PaymentDate", models.DateField(null=True)),
                (
                    "Imsuser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaryinfo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StaffName", models.CharField(max_length=150, null=True)),
                ("EmployID", models.CharField(max_length=150, null=True)),
                ("StaffDesignation", models.CharField(max_length=150, null=True)),
                ("JoinDate", models.DateField(auto_now_add=True, null=True)),
                ("StaffPhoto", models.ImageField(null=True, upload_to="staffphoto")),
                (
                    "Imsuser",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StudentID", models.CharField(max_length=100, null=True)),
                ("StudentName", models.CharField(max_length=100, null=True)),
                (
                    "StudentPhoto",
                    models.ImageField(null=True, upload_to="studentPhoto"),
                ),
                ("AdmissionDate", models.DateField(auto_now_add=True, null=True)),
                (
                    "EducationalQualification",
                    models.CharField(max_length=100, null=True),
                ),
                ("LinkedInLink", models.CharField(max_length=150, null=True)),
                ("GithubLink", models.CharField(max_length=150, null=True)),
                ("FacebookLink", models.CharField(max_length=150, null=True)),
                (
                    "Imsuser",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentinfo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAttendanceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Attendance",
                    models.CharField(
                        choices=[("Present", "Present"), ("Absent", "Absent")],
                        default="Absent",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("Date", models.DateField(null=True)),
                (
                    "BatchNo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myApp.batchinfomodel",
                    ),
                ),
                (
                    "Student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myApp.studentmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Review", models.TextField(null=True)),
                ("ReviewDate", models.DateField(auto_now_add=True, null=True)),
                (
                    "Status",
                    models.CharField(default="Pending", max_length=50, null=True),
                ),
                (
                    "CourseName",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewcourseinfo",
                        to="myApp.courseinfomodel",
                    ),
                ),
                (
                    "Imsuser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewinfo",
                        to="myApp.studentmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdmittedCourseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StudentID", models.CharField(max_length=150, null=True)),
                ("CourseFee", models.CharField(max_length=150, null=True)),
                ("Payment", models.CharField(max_length=150, null=True)),
                ("Due", models.CharField(max_length=150, null=True)),
                ("AdmissionDate", models.DateField(auto_now_add=True, null=True)),
                (
                    "Courseuser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admittedcourseinfo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "LearningBatch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batchinfo",
                        to="myApp.batchinfomodel",
                    ),
                ),
                (
                    "CourseName",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courseinfo",
                        to="myApp.courseinfomodel",
                    ),
                ),
                (
                    "Studentuser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studetinfo",
                        to="myApp.studentmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EmployID", models.CharField(max_length=100, null=True)),
                ("TeacherName", models.CharField(max_length=100, null=True)),
                ("Designation", models.CharField(max_length=100, null=True)),
                ("Skills", models.CharField(max_length=100, null=True)),
                ("LinkedInLink", models.CharField(max_length=150, null=True)),
                ("GithubLink", models.CharField(max_length=150, null=True)),
                ("FacebookLink", models.CharField(max_length=150, null=True)),
                ("JoinDate", models.DateField(auto_now_add=True, null=True)),
                (
                    "TeacherPhoto",
                    models.ImageField(null=True, upload_to="teacherphoto"),
                ),
                (
                    "Imsuser",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacherinfo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherBatchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacherbatch",
                        to="myApp.batchinfomodel",
                    ),
                ),
                (
                    "teacheruser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacherbatchinfo",
                        to="myApp.teachermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Attendance",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Pending", "Pending"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("Date", models.DateField(null=True)),
                ("date_time", models.DateTimeField(null=True)),
                (
                    "Teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myApp.teachermodel",
                    ),
                ),
            ],
        ),
    ]
